### ISSUE TITLE
Placeholders are not being replaced

### ISSUE THREAD

**Issue by Tickolas** [ammeep/electron-accelerator#18]
Hey there!

First off, great presentation at NordicJS. Really inspired me to give Electron a shot =) 

However, I'm having some issues getting the Accelerator to work properly. I go through the wizard entering name, description etc., but package.json and config.json still contain placeholders like {{application-name}}. This causes the bootstrap and build scripts to fail, naturally. I've tried this on both Mac and Windows, getting the same result. 

When replacing these placeholders manually I can get a Windows executable out of it, but it crashes referring to "Error: Update URL is not set at SquirrelUpdater.checkForUpdates()" etc. This happens no matter what I enter into the optional variables. Any ideas on how to get past this?

**Comment by ammeep** [comment]
>I go through the wizard entering name, description etc., but package.json and config.json still contain placeholders like {{application-name}}

Hi @Tickolas this should indeed not be happening. Are you able to please run ``electron-accelerator -v`` and let me know which version you are running?

**Comment by Tickolas** [comment]
Sure thing, @ammeep. Looks like version 0.0.4.

**Comment by ammeep** [comment]
Thank you @Tickolas. Honestly I'm not sure why this is not working for you, so I'm working on an update which will allow you to pass in a --debug flag so we can see what is going on.

In the meantime, could you please give me an example of how you are running the command?

**Comment by AndreasArledal** [comment]
Happens here too.
Version 0.0.4
Mac OSX Yosemite 10.10.5
Tried on node v0.10.38, v4.1.1 and iojs-v2.5.0

Latest on master works well though.

**Comment by ammeep** [comment]
@AndreasArledal thanks for testing out master! I have one small improvement I want to ship before pushing an update to npm. Hopefully I'll have out 0.0.5 over the weekend.

**Comment by paulobarcelos** [comment]
Hey @ammeep, I am another one that got inspired to give Electron a shot after your NordicJS presentation. Awesome stuff!

Have you pushed any updates to NPM?
I am having the issue too...

**Comment by ammeep** [comment]
I'm working on fix for this here https://github.com/ammeep/electron-accelerator/pull/24
It's named terribad, but essentially I'm ripping out the old way of gathering args from the CLI. I  have also added a debug option so we can get a glimpse if this happens again. I'll get this out as fast as I can and let you all know :+1:

**Comment by ammeep** [comment]
Hey there folks. Sorry for the delay - life got in the way... you know how it is. 

I've overhauled the way the scripts work, to make way for other updating mechanism. And as part of that, this will have been fixed. 0.0.5 is up on NPM now. https://www.npmjs.com/package/electron-accelerator. Please check the read me for CLI changes :+1:
