### ISSUE TITLE
Question: should we build for windows on windows?

### ISSUE THREAD

**Issue by havenchyk** [ammeep/electron-accelerator#35]
Hi @ammeep, thanks for your package, it's really cool.

Could you please describe one thing, that I found in sources: 

```
if (process.platform !== 'win32') {
      grunt.log.warn('Skipping creating win32 distributable because the current platform is not win32')
      return
}
```

is it only for grunt-electron-installer? But in general: should we make a build for e.g. windows only on windows, what is the preferred way?

**Comment by plrthink** [comment]
@havenchyk I guess this is for grunt-electron-installer before v1.1.0, but after that version the grunt-electron-installer has the ability to build a installer on no-windows machine thanks to this PR:

https://github.com/atom/grunt-electron-installer/pull/80

Haven't test it yet, but it seems like it works according to the comments.

**Comment by havenchyk** [comment]
@plrthink yep, there are some problems, I tried :) It can't create `.msi` file, only `.exe`

In general, I'm wondering, what is the preferred way to make `.msi` installer. And if it's a grunt-electron-installer, must we use windows or not? Or it's up to developer?

**Comment by plrthink** [comment]
@havenchyk I don't know the reason for using `.msi` over `.exe`, and I just ship `.exe` to my end users. As for me, I have a windows machine to build my electron app and to test it. I think maybe other package similar to `grunt-electron-installer` can create a installer on no-windows machine but you still need one to test it.
